### ISSUE TITLE
Android POS/KDS

### ISSUE THREAD

**Issue by okdistribute** [getditto/demoapp-pos-kds#25]
An android version of this app with all of the same functionality.

This should be in DQL, which means that the iOS version will also need to be converted to DQL as part of a separate piece of work.

**Comment by rajramsaroop** [comment]
I have been working on this whenever I get time and I pretty much have an MVP ready for publishing to the Play store. The app can be built from the `main` branch under the `Android` directory. Would be grateful for any testing and messing around with it before I publish to the Play store.

Known issues/missing features:
- Custom Locations
- Evictions (though I don't think the iOS version has this?)
- A few minor UI issues, but no showstoppers (i.e. nothing broken)
- No heartbeat config
- No interface to change log level

Besides that, the app works fully in demo mode and has feature parity with iOS. It also syncs with other Android devices as well as the iOS app. The app also features the Android Tools Viewer integration, so all tools are available.

Besides the known issues stated above, there is some code refactoring I'd like to do as I'd like it to be a good example of an Android app integrating with Ditto. 

I will be making a Loom video demo soon as well!

**Comment by rajramsaroop** [comment]
GH issues have been created in the repo for remaining items and bugs/issues.

Also created a GH issue for publishing to the Play Store so I think we can close this one out!
