### ISSUE TITLE
Add Permissions Health Tool and attach data to Heartbeat

### ISSUE THREAD

**Issue by bplattenburg** [getditto/demoapp-pos-kds#44]
Add the Permissions Health tool from DittoSwiftTools and connect it to the Heartbeat tool now as a custom health metric (depends on https://github.com/getditto/DittoSwiftTools/issues/100). This can be used to demonstrate how customers can attach custom metrics for remote monitoring.

**Comment by texasRanger09** [comment]
Add `HealthMetricProvider` protocol to Permissions Health.
