### ISSUE TITLE
Heartbeat tool stops working if the heartbeat screen is closed

### ISSUE THREAD

**Issue by bplattenburg** [getditto/demoapp-pos-kds#48]
When recording a recent demo, I noticed the heartbeat stopped running anytime I left the screen we use to configure the heartbeat. I suspect we have something that is only referenced in that view code that should be extracted to somewhere that runs no matter what screen you're on and whether the app is backgrounded.

**Comment by texasRanger09** [comment]
Do you know if the Heartbeat stopped or just the Ditto subscription for it stopped?
