### ISSUE TITLE
Setup to demonstrate using system parameter to prefer redundant bluetooth

### ISSUE THREAD

**Issue by bplattenburg** [getditto/demoapp-pos-kds#50]
Update to 4.7.2 and use `ALTER SYSTEM` to set `mesh_chooser_avoid_redundant_bluetooth` to `false` for this app

```swift
Task { [weak self] in
    do {
        try await ditto.store.execute("ALTER SYSTEM SET mesh_chooser_avoid_redundant_bluetooth = false")
    }
}
```

As discussed in [Slack](https://dittolive.slack.com/archives/C010MNVAY7N/p1718113885182009)

**Comment by bplattenburg** [comment]
Given the default behavior will flip back in the upcoming 4.8.0 release, this might not be worth doing after all

**Comment by okdistribute** [comment]
Yeah sounds good
